### ISSUE TITLE
AutoConfig & Setup

### ISSUE THREAD

**Issue by upconett** [upconett/HwSystem_bot#1]
Setup database and bot config on first startup. 

### On Startup

- Assign **main-bot** and **minimal-logger-bot** Tokens in terminal.

- Add **creator ID to config** ([learn your id](https://t.me/getmyid_bot)) in terminal.

- Type in **database connection** properties in terminal.

- Automatically create database columns if all instances are connected succesfully.

**Comment by ppljc** [comment]
@Stepan0Tap What a nice issue!
